// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHViVunx7OhwW4sc9i-QwOzXlFQbyFQHA',
    appId: '1:965207903573:web:10e47d9d130739eb3c73dc',
    messagingSenderId: '965207903573',
    projectId: 'chucknorrisapp-260f5',
    authDomain: 'chucknorrisapp-260f5.firebaseapp.com',
    storageBucket: 'chucknorrisapp-260f5.appspot.com',
    measurementId: 'G-BVCVME43J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdvN2eUJDktkJPRjxVfnjKhF7UlOBvTY',
    appId: '1:965207903573:android:28b15188de17cdc73c73dc',
    messagingSenderId: '965207903573',
    projectId: 'chucknorrisapp-260f5',
    storageBucket: 'chucknorrisapp-260f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcamZo8Pi7Vn3mZ-nu0Akzry8FXRBxOJQ',
    appId: '1:965207903573:ios:eb80279d9ea5dce03c73dc',
    messagingSenderId: '965207903573',
    projectId: 'chucknorrisapp-260f5',
    storageBucket: 'chucknorrisapp-260f5.appspot.com',
    iosClientId: '965207903573-46rh98ojg54o8na52jh34njunt374iqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chuckNorrisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcamZo8Pi7Vn3mZ-nu0Akzry8FXRBxOJQ',
    appId: '1:965207903573:ios:eb80279d9ea5dce03c73dc',
    messagingSenderId: '965207903573',
    projectId: 'chucknorrisapp-260f5',
    storageBucket: 'chucknorrisapp-260f5.appspot.com',
    iosClientId: '965207903573-46rh98ojg54o8na52jh34njunt374iqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chuckNorrisApp',
  );
}
